# .github/workflows/deploy.yml
name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y sshpass

      - name: Deploy to VM
        env:
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        run: |
          sshpass -p "$VM_PASSWORD" ssh -o StrictHostKeyChecking=no $VM_USERNAME@139.180.210.216 << 'EOF'
            cd ~/belajarflask
            git pull origin main
            # Optional: Install dependencies or restart services
            # Example for a Python Flask application:
            # source venv/bin/activate
            # pip install -r requirements.txt
            # sudo systemctl restart your-service
            exit
          EOF